USE [Data]
GO

/****** Object:  Table [dbo].[RAN]    Script Date: 08/18/2014 12:15:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RAN](
	[RID] [bigint] IDENTITY(1,1) NOT NULL,
	[Record] [float] NOT NULL,
 CONSTRAINT [PK__RAN__CAFF41322F10007B] PRIMARY KEY CLUSTERED 
(
	[RID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


